name: Export theme

on:
  workflow_dispatch:
    inputs:
      themeId:
        description: 'Theme ID'
        required: true

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm ci --prefix ./.github/workflows/scripts/

      - name: Run script
        run: node ./.github/workflows/scripts/exportTheme.js ${{ github.event.inputs.themeId }}
        env:
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_TOKEN: ${{ secrets.ZENDESK_TOKEN }}

      - name: Upload theme file
        uses: actions/upload-artifact@v2
        with:
          name: theme-file
          path: ./theme_${{ github.event.inputs.themeId }}.zip
