name: Publish theme

on:
  workflow_dispatch:
    inputs:
      themeId:
        description: 'Theme ID'
        required: true
      scriptBranch:
        description: 'Run scripts from'
        required: true
        default: 'main'

jobs:
  publish_theme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Check out publishTheme.js
        uses: Bhacaz/checkout-files@v2
        with:
          files: '.github/workflows/scripts/publishTheme.js'
          branch: ${{ github.event.inputs.scriptBranch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci --prefix ./.github/workflows/scripts/

      - name: Run publishTheme.js
        run: node ./.github/workflows/scripts/publishTheme.js ${{ github.event.inputs.themeId }}
        env:
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_TOKEN: ${{ secrets.ZENDESK_TOKEN }}
