name: Update theme

on:
  workflow_dispatch:
    inputs:
      themeId:
        description: 'Theme ID'
        type: string
        required: true
        default: ''
      branchName:
        description: 'Branch Name'
        type: string
        required: false
        default: ''
      scriptBranch:
        description: 'Run scripts from'
        type: string
        required: true
        default: 'main'
      replaceSettings:
        description: 'Replace Settings'
        type: boolean
        required: true
        default: true

jobs:
  update_theme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branchName || github.ref }}

      - name: Check out updateTheme.js
        uses: Bhacaz/checkout-files@v2
        with:
          files: '.github/workflows/scripts/updateTheme.js'
          branch: ${{ github.event.inputs.scriptBranch }}

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm ci --prefix ./.github/workflows/scripts/

      - name: Zip theme files
        run: |
          zip -r theme.zip . -x ".*"
          mv theme.zip ./.github/workflows/scripts/

      - name: Run updateTheme.js
        run: node ./.github/workflows/scripts/updateTheme.js ${{ github.event.inputs.themeId }} ./.github/workflows/scripts/theme.zip ${{ github.event.inputs.replaceSettings }}
        env:
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_TOKEN: ${{ secrets.ZENDESK_TOKEN }}

      - name: Upload theme file
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: theme-file
          path: ./.github/workflows/scripts/theme.zip
